name: Leetcode-go
on: [push]
jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.16
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.3
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Restore vendor cache
      uses: actions/cache@v2
      id: cache
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-build-{{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Vendor module
      run: go mod vendor

    - name: Run tests
      run: go test ./...
